// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ScrapeM")>]
[<assembly: AssemblyProductAttribute("ScrapeM")>]
[<assembly: AssemblyDescriptionAttribute("A monadic web scraping library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ScrapeM"
    let [<Literal>] AssemblyProduct = "ScrapeM"
    let [<Literal>] AssemblyDescription = "A monadic web scraping library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
